FROM  --platform=linux/arm64 ubuntu:20.04 AS builder

ARG NETWORK=live
ARG CI_TAG=DEV_BUILD
ARG CI_BUILD=OFF

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq update && apt-get -yqq install make cmake git p7zip-full g++ qt5-default wget \
build-essential \
zlib1g-dev

RUN cd /tmp && git clone https://github.com/Xunil32/nano-workspace.git && cd /tmp/nano-workspace
WORKDIR /tmp/nano-workspace
RUN make build
RUN echo ${NETWORK} >/etc/nano-network

FROM --platform=linux/arm64 ubuntu:20.04 AS node
ENV DEBIAN_FRONTEND=noninteractive

RUN groupadd --gid 1000 nanocurrency

COPY --from=builder /tmp/nano-workspace/build/nano_node /usr/bin
COPY --from=builder /tmp/nano-workspace/build/nano_rpc /usr/bin
COPY --from=builder /tmp/nano-workspace/build/nano_pow_server /usr/bin
COPY --from=builder /tmp/nano-workspace/nano-node/api/ /usr/bin/api/
COPY --from=builder /tmp/nano-workspace/boost/boost_1_80_0/stage/lib/*  /usr/local/lib/
COPY --from=builder /etc/nano-network /etc
COPY node/entry.sh /usr/bin/entry.sh
COPY node/config /usr/share/nano/config
RUN chmod +x /usr/bin/entry.sh
RUN ln -s /usr/bin/nano_node /usr/bin/rai_node
RUN ldconfig

WORKDIR /root
USER root

RUN useradd --uid 1000 --gid nanocurrency --shell /bin/bash --create-home nanocurrency

ENV PATH="${PATH}:/usr/bin"
ENTRYPOINT ["/usr/bin/entry.sh"]
CMD ["nano_node", "daemon", "-l"]


